<template>

  <div class="about">
    <h2>This is an about page</h2>
    <br/>
    <p> This is an online <b>IPAQ questionaire tool</b> developed by the University of Hasselt (Belgium).</p> <br/> 
    <h2> Our GDPR policy </h2> <!-- https://gdpr.eu/privacy-notice/ -->
    <br>

    <ol style="color: rgb(70, 72, 85); font-family: Helvetica, Arial, sans-serif; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <li>
        <h3 id="isPasted" style='box-sizing: border-box; margin: 0px 0px 2rem; font-family: "Open Sans", Arial, Helvetica, sans-serif; font-weight: 700; line-height: 1.2; color: rgb(0, 0, 0); font-size: 2rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>What data do we collect?</h3>
        <p style='box-sizing: border-box; margin: 0px 0px 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>Our Company collects the following data:</p>
        <ul style='box-sizing: border-box; margin-top: 0px; margin-bottom: 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
            <li style="box-sizing: border-box; line-height: 24px;">Personal identification information (Name, email address, phone number, etc.)</li>
            <li style="box-sizing: border-box; line-height: 24px;">[Add any other data your company collects]</li>
        </ul>
    </li>

    <li>
        <h3 style='box-sizing: border-box; margin: 0px 0px 2rem; font-family: "Open Sans", Arial, Helvetica, sans-serif; font-weight: 700; line-height: 1.2; color: rgb(0, 0, 0); font-size: 2rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>How do we collect your data?</h3>
        <p style='box-sizing: border-box; margin: 0px 0px 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>You directly provide Our Company with most of the data we collect. We collect data and process data when you:</p>
        <ul style='box-sizing: border-box; margin-top: 0px; margin-bottom: 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
            <li style="box-sizing: border-box; line-height: 24px;">Register online or place an order for any of our products or services.</li>
            <li style="box-sizing: border-box; line-height: 24px;">Voluntarily complete a customer survey or provide feedback on any of our message boards or via email.</li>
            <li style="box-sizing: border-box; line-height: 24px;">Use or view our website via your browser&rsquo;s cookies.</li>
            <li style="box-sizing: border-box; line-height: 24px;">[Add any other ways your company collects data]</li>
        </ul>
    </li>

    <li>
        <p style='box-sizing: border-box; margin: 0px 0px 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>Our Company may also receive your data indirectly from the following sources:</p>
        <ul style='box-sizing: border-box; margin-top: 0px; margin-bottom: 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
            <li style="box-sizing: border-box; line-height: 24px;">[Add any indirect source of data your company has]</li>
        </ul>
    </li>
    <li>
        <h3 style='box-sizing: border-box; margin: 0px 0px 2rem; font-family: "Open Sans", Arial, Helvetica, sans-serif; font-weight: 700; line-height: 1.2; color: rgb(0, 0, 0); font-size: 2rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>How will we use your data?</h3>
        <p style='box-sizing: border-box; margin: 0px 0px 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>Our Company collects your data so that we can:</p>
        <ul style='box-sizing: border-box; margin-top: 0px; margin-bottom: 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
            <li style="box-sizing: border-box; line-height: 24px;">Process your order and manage your account.</li>
            <li style="box-sizing: border-box; line-height: 24px;">Email you with special offers on other products and services we think you might like.</li>
            <li style="box-sizing: border-box; line-height: 24px;">[Add how else your company uses data]</li>
        </ul>
    </li>

    <li>
        <p style='box-sizing: border-box; margin: 0px 0px 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>If you agree, Our Company will share your data with our partner companies so that they may offer you their products and services.</p>
        <ul style='box-sizing: border-box; margin-top: 0px; margin-bottom: 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
            <li style="box-sizing: border-box; line-height: 24px;">[List organizations that will receive data]</li>
        </ul>
    </li>
    <li>
        <p style='box-sizing: border-box; margin: 0px 0px 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>When Our Company processes your order, it may send your data to, and also use the resulting information from, credit reference agencies to prevent fraudulent purchases.</p>
        <h3 style='box-sizing: border-box; margin: 0px 0px 2rem; font-family: "Open Sans", Arial, Helvetica, sans-serif; font-weight: 700; line-height: 1.2; color: rgb(0, 0, 0); font-size: 2rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>How do we store your data?</h3>
        <p style='box-sizing: border-box; margin: 0px 0px 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>Our Company securely stores your data at [enter the location and describe security precautions taken].</p>
        <p style='box-sizing: border-box; margin: 0px 0px 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>Our Company will keep your [enter type of data] for [enter time period]. Once this time period has expired, we will delete your data by [enter how you delete users&rsquo; data].</p>
        <h3 style='box-sizing: border-box; margin: 0px 0px 2rem; font-family: "Open Sans", Arial, Helvetica, sans-serif; font-weight: 700; line-height: 1.2; color: rgb(0, 0, 0); font-size: 2rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>Marketing</h3>
        <p style='box-sizing: border-box; margin: 0px 0px 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>Our Company would like to send you information about products and services of ours that we think you might like, as well as those of our partner companies.</p>
        <ul style='box-sizing: border-box; margin-top: 0px; margin-bottom: 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
            <li style="box-sizing: border-box; line-height: 24px;">[List organizations that will receive data]</li>
        </ul>
    </li>
    <li>
        <p style='box-sizing: border-box; margin: 0px 0px 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>If you have agreed to receive marketing, you may always opt out at a later date.</p>
        <p style='box-sizing: border-box; margin: 0px 0px 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>You have the right at any time to stop Our Company from contacting you for marketing purposes or giving your data to other members of the Our Company Group.</p>
        <p style='box-sizing: border-box; margin: 0px 0px 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>If you no longer wish to be contacted for marketing purposes, please click here.</p>
        <h3 style='box-sizing: border-box; margin: 0px 0px 2rem; font-family: "Open Sans", Arial, Helvetica, sans-serif; font-weight: 700; line-height: 1.2; color: rgb(0, 0, 0); font-size: 2rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>What are your data protection rights?</h3>
        <p style='box-sizing: border-box; margin: 0px 0px 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>Our Company would like to make sure you are fully aware of all of your data protection rights. Every user is entitled to the following:</p>
        <p style='box-sizing: border-box; margin: 0px 0px 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'><strong style="box-sizing: border-box; font-weight: 700;">The right to access</strong> &ndash; You have the right to request Our Company for copies of your personal data. We may charge you a small fee for this service.</p>
        <p style='box-sizing: border-box; margin: 0px 0px 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'><strong style="box-sizing: border-box; font-weight: 700;">The right to rectification</strong> &ndash; You have the right to request that Our Company correct any information you believe is inaccurate. You also have the right to request Our Company to complete the information you believe is incomplete.</p>
        <p style='box-sizing: border-box; margin: 0px 0px 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'><strong style="box-sizing: border-box; font-weight: 700;">The right to erasure</strong> &ndash; You have the right to request that Our Company erase your personal data, under certain conditions.</p>
        <p style='box-sizing: border-box; margin: 0px 0px 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'><strong style="box-sizing: border-box; font-weight: 700;">The right to restrict processing</strong> &ndash; You have the right to request that Our Company restrict the processing of your personal data, under certain conditions.</p>
        <p style='box-sizing: border-box; margin: 0px 0px 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'><strong style="box-sizing: border-box; font-weight: 700;">The right to object to processing</strong> &ndash; You have the right to object to Our Company&rsquo;s processing of your personal data, under certain conditions.</p>
        <p style='box-sizing: border-box; margin: 0px 0px 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'><strong style="box-sizing: border-box; font-weight: 700;">The right to data portability</strong> &ndash; You have the right to request that Our Company transfer the data that we have collected to another organization, or directly to you, under certain conditions.</p>
        <p style='box-sizing: border-box; margin: 0px 0px 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us at our email:</p>
        <p style='box-sizing: border-box; margin: 0px 0px 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>Call us at:</p>
        <p style='box-sizing: border-box; margin: 0px 0px 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>Or write to us:</p>
        <h3 style='box-sizing: border-box; margin: 0px 0px 2rem; font-family: "Open Sans", Arial, Helvetica, sans-serif; font-weight: 700; line-height: 1.2; color: rgb(0, 0, 0); font-size: 2rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>Cookies</h3>
        <p style='box-sizing: border-box; margin: 0px 0px 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>Cookies are text files placed on your computer to collect standard Internet log information and visitor behavior information. When you visit our websites, we may collect information from you automatically through cookies or similar technology</p>
        <p style='box-sizing: border-box; margin: 0px 0px 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>For further information, visit allaboutcookies.org.</p>
        <h3 style='box-sizing: border-box; margin: 0px 0px 2rem; font-family: "Open Sans", Arial, Helvetica, sans-serif; font-weight: 700; line-height: 1.2; color: rgb(0, 0, 0); font-size: 2rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>How do we use cookies?</h3>
        <p style='box-sizing: border-box; margin: 0px 0px 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>Our Company uses cookies in a range of ways to improve your experience on our website, including:</p>
        <ul style='box-sizing: border-box; margin-top: 0px; margin-bottom: 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
            <li style="box-sizing: border-box; line-height: 24px;">Keeping you signed in</li>
            <li style="box-sizing: border-box; line-height: 24px;">Understanding how you use our website</li>
            <li style="box-sizing: border-box; line-height: 24px;">[Add any uses your company has for cookies]</li>
        </ul>
        
    </li>

    <li>
        <h3 style='box-sizing: border-box; margin: 0px 0px 2rem; font-family: "Open Sans", Arial, Helvetica, sans-serif; font-weight: 700; line-height: 1.2; color: rgb(0, 0, 0); font-size: 2rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>What types of cookies do we use?</h3>
        <p style='box-sizing: border-box; margin: 0px 0px 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>There are a number of different types of cookies, however, our website uses:</p>
        <ul style='box-sizing: border-box; margin-top: 0px; margin-bottom: 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
            <li style="box-sizing: border-box; line-height: 24px;">Functionality &ndash; Our Company uses these cookies so that we recognize you on our website and remember your previously selected preferences. These could include what language you prefer and location you are in. A mix of first-party and third-party cookies are used.</li>
            <li style="box-sizing: border-box; line-height: 24px;">Advertising &ndash; Our Company uses these cookies to collect information about your visit to our website, the content you viewed, the links you followed and information about your browser, device, and your IP address. Our Company sometimes shares some limited aspects of this data with third parties for advertising purposes. We may also share online data collected through cookies with our advertising partners. This means that when you visit another website, you may be shown advertising based on your browsing patterns on our website.</li>
            <li style="box-sizing: border-box; line-height: 24px;">[Add any other types of cookies your company uses]</li>
        </ul>
    </li>
    <li>
        <h3 style='box-sizing: border-box; margin: 0px 0px 2rem; font-family: "Open Sans", Arial, Helvetica, sans-serif; font-weight: 700; line-height: 1.2; color: rgb(0, 0, 0); font-size: 2rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>How to manage cookies</h3>
        <p style='box-sizing: border-box; margin: 0px 0px 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>You can set your browser not to accept cookies, and the above website tells you how to remove cookies from your browser. However, in a few cases, some of our website features may not function as a result.</p>
        <h3 style='box-sizing: border-box; margin: 0px 0px 2rem; font-family: "Open Sans", Arial, Helvetica, sans-serif; font-weight: 700; line-height: 1.2; color: rgb(0, 0, 0); font-size: 2rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>Privacy policies of other websites</h3>
        <p style='box-sizing: border-box; margin: 0px 0px 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>The Our Company website contains links to other websites. Our privacy policy applies only to our website, so if you click on a link to another website, you should read their privacy policy.</p>
        <h3 style='box-sizing: border-box; margin: 0px 0px 2rem; font-family: "Open Sans", Arial, Helvetica, sans-serif; font-weight: 700; line-height: 1.2; color: rgb(0, 0, 0); font-size: 2rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>Changes to our privacy policy</h3>
        <p style='box-sizing: border-box; margin: 0px 0px 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>Our Company keeps its privacy policy under regular review and places any updates on this web page. This privacy policy was last updated on 9 January 2019.</p>
        <h3 style='box-sizing: border-box; margin: 0px 0px 2rem; font-family: "Open Sans", Arial, Helvetica, sans-serif; font-weight: 700; line-height: 1.2; color: rgb(0, 0, 0); font-size: 2rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>How to contact us</h3>
        <p style='box-sizing: border-box; margin: 0px 0px 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>If you have any questions about Our Company&rsquo;s privacy policy, the data we hold on you, or you would like to exercise one of your data protection rights, please do not hesitate to contact us.</p>
        <p style='box-sizing: border-box; margin: 0px 0px 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>Email us at:</p>
        <p style='box-sizing: border-box; margin: 0px 0px 2rem; color: rgb(0, 0, 0); font-family: "Open Sans", Arial, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>Call us:</p>
    </li>
</ol>
</div>
  
</template>
